---
name: SDL-Tutorial-Tetris
version: 0.02
author: []
abstract: tetris game using SDL(2)
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::XSAccessor: 1.03
  Readonly: 1.03
  SDL: v2.2.2.17
configure_requires:
  Module::Build: 0.34
provides:
  SDL::Tutorial::Tetris:
    file: lib/SDL/Tutorial/Tetris.pm
    version: 0.02
  SDL::Tutorial::Tetris::Base:
    file: lib/SDL/Tutorial/Tetris/Base.pm
    version: 0.01
  SDL::Tutorial::Tetris::Controller::CPUSpinner:
    file: lib/SDL/Tutorial/Tetris/Controller/CPUSpinner.pm
  SDL::Tutorial::Tetris::Controller::Game:
    file: lib/SDL/Tutorial/Tetris/Controller/Game.pm
  SDL::Tutorial::Tetris::Controller::Keyboard:
    file: lib/SDL/Tutorial/Tetris/Controller/Keyboard.pm
  SDL::Tutorial::Tetris::EventManager:
    file: lib/SDL/Tutorial/Tetris/EventManager.pm
  SDL::Tutorial::Tetris::Model::Grid:
    file: lib/SDL/Tutorial/Tetris/Model/Grid.pm
  SDL::Tutorial::Tetris::Model::Pieces:
    file: lib/SDL/Tutorial/Tetris/Model/Pieces.pm
  SDL::Tutorial::Tetris::View::Game:
    file: lib/SDL/Tutorial/Tetris/View.pm
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
